////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// main.tsx
// Code is modified from MongoDB MERN tutorial
//
// Here we create routes for react_router_dom to make our single-page application. We create paths and depending on
// whats on those paths, when we call <App/>, <App/> will display and <Outlet/> will as well if called, 
// and <Outlet/> will be the children components laid out. We also render our router generated by our routes
// starting on "/" as the root.
//
// Assembled by Alex Paz.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////

import * as React from "react";
import * as ReactDOM from "react-dom/client";
import {
  createBrowserRouter,
  RouterProvider,
  RouteObject,
} from "react-router-dom";
import App from "./App";
import Recipe from "./components/Recipe";
import RecipeList from "./components/RecipeList";
import "./index.css";

const routes: RouteObject[] = [
  {
    path: "/",
    element: <App />,
    children: [
      {
        path: "/",
        element: <RecipeList />,
      },
    ],
  },
  {
    path: "/edit/:id",
    element: <App />,
    children: [
      {
        path: "/edit/:id",
        element: <Recipe />,
      },
    ],
  },
  {
    path: "/create",
    element: <App />,
    children: [
      {
        path: "/create",
        element: <Recipe />,
      },
    ],
  },
];

const router = createBrowserRouter(routes);

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);